print("What is your name human?")
user_name = input()
print("How old are you (in years)?")
user_age = int(input())
print("How tall are you (in meters)?")
user_height = float(input())
print("How much do you weigh (in kilograms)?")
user_weight = int(input())
print(user_name, "you are", user_age, "years old and your BMI is", user_weight/user_height)