# Display message to the standard output
print("System Failure Imminent!")
print("System reboot has been initiated...")
print()
print("...rebooting sensory system")
print("...rebooting output motors")
print("...rebooting hover engine")
print()
print("System online.")
# Display escape characters
print("\n Displays a new line")
print("\t Displays a tab space")
print("\\ Displays a back slash")
print("\" Displays a double quote")
print("\' Displays a single quote")
print("\n")
print("\t \"I am Beep!\"")