print("How many mountains should I display?")
user_response = int(input())
print()
print("Displaying ...")
for count in range(0, user_response, 1):
    print("       __")
    print("      /  \_ ")
    print("     /^    \ ")
    print("    /  ^    \_")
    print("  _/ ^ ^     ^\ ")
    print(" /  ^     ^    \ ")
    print()
print("Done!")